name: "Words"
description: "Personal blog of Benjamin Fritz"

author: "Benjamin Fritz"

url: "http://benjaminfritz.co"
baseurl: /blog

markdown: redcarpet
permalink: :year/:month/:title.html
pygments: true
