# Dependencies
markdown:         redcarpet
pygments:         true
baseurl:          /blog

# Permalinks
permalink:        pretty

# Setup
title:            Words
tagline:          'By Benjamin Fritz'
description:      'Bits and Blurbs by Interaction Designer Benjamin Fritz'
url:              http://benjaminfritz.co/blog

author:
  name:           'Benjamin Fritz'
  url:            http://benjaminfritz.co

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
