name: "Elaborate, please"
description: "Personal blog of Benjamin Fritz"

author: "Benjamin Fritz"

url: "http://benjaminfritz.co"
baseurl: /words

markdown: redcarpet
permalink: :year/:month/:title.html
pygments: true
