name: Words
tagline: "By Benjamin Fritz"
description: "Bits and Blurbs by Interaction Designer Benjamin Fritz"

author: "Benjamin Fritz"

markdown: redcarpet
permalink: pretty
pygments: true
baseurl: /blog/

paginate: 5
